/**
 * CadQuery / build123d emitter: FeatureProgram → a standalone, traced Python script.
 *
 * @layer core/codegen
 * @pure
 * @invariant running the script records LLULL_TRACE, which apply_code_trace turns back into the same
 *   llull feature history (parameters + expressions + order) — the code is a round-trippable recipe.
 */

import type { Feature, FeatureProgram, ShapeSpec, Term, Term2, Term3 } from './featureProgram';
import {
  formatDegrees,
  formatNumber,
  formatTerm,
  isZero,
  numberRows,
  provenance,
  quote,
  stepHeading,
} from './format';
import { pythonRuntime, type PythonBackend } from './pythonRuntime';

const LIBRARY: Readonly<Record<PythonBackend, string>> = {
  cadquery: 'CadQuery',
  build123d: 'build123d',
};

function tuple(terms: readonly Term[]): string {
  return `(${terms.map(formatTerm).join(', ')})`;
}

function points(profile: readonly Term2[]): string {
  return `[${profile.map((p) => tuple(p)).join(', ')}]`;
}

function shapeCall(shape: ShapeSpec): string {
  switch (shape.kind) {
    case 'box':
      return `box(${tuple(shape.size)}`;
    case 'cylinder':
      return `cylinder(${formatTerm(shape.radius)}, ${formatTerm(shape.height)}`;
    case 'sphere':
      return `sphere(${formatTerm(shape.radius)}`;
    case 'cone':
      return `cone(${formatTerm(shape.radius)}, ${formatTerm(shape.height)}`;
    case 'torus':
      return `torus(${formatTerm(shape.ringRadius)}, ${formatTerm(shape.tubeRadius)}`;
    case 'wedge':
      return `wedge(${tuple(shape.size)}`;
    case 'pyramid':
      return `pyramid(${formatTerm(shape.baseWidth)}, ${formatTerm(shape.baseDepth)}, ${formatTerm(shape.height)}`;
    case 'extrusion':
      return `extrude(${points(shape.profile)}, ${formatTerm(shape.depth)}`;
    case 'revolution':
      return (
        `revolve(${points(shape.profile)}, axis=${quote(shape.axis)}, ` +
        `angle=${formatDegrees(shape.angle, 'math.pi')}, segments=${shape.segments}`
      );
    case 'mesh':
      return `mesh([\n    ${numberRows(shape.positions, 9).join(',\n    ')},\n]`;
  }
}

function placement(position: Term3, rotation: Term3): string {
  let text = '';
  if (!isZero(position)) text += `, position=${tuple(position)}`;
  if (!isZero(rotation)) {
    text += `, rotation=(${rotation.map((r) => formatDegrees(r, 'math.pi')).join(', ')})`;
  }
  return text;
}

function featureLine(feature: Feature): string {
  const v = feature.variable;
  switch (feature.op) {
    case 'solid': {
      const name = feature.name !== undefined ? `, name=${quote(feature.name)}` : '';
      const place =
        feature.shape.kind === 'mesh' ? '' : placement(feature.position, feature.rotation);
      return `${v} = ${shapeCall(feature.shape)}${place}, color=${quote(feature.color)}${name})`;
    }
    case 'boolean':
      return `${v} = ${feature.kind}(${feature.left}, ${feature.right})`;
    case 'translate':
      return `${v} = translate(${v}, ${tuple(feature.delta)})`;
    case 'remove':
      return `remove(${v})`;
    case 'label':
      return `label(${v}, ${quote(feature.name)})`;
  }
}

function header(program: FeatureProgram, backend: PythonBackend): string {
  return [
    '"""',
    `llull model — generated by llull export_code (${LIBRARY[backend]}).`,
    '',
    ...provenance(program),
    'Positions are in document units; rotations are XYZ Euler angles in DEGREES',
    '(applied about Z, then Y, then X, around the solid origin).',
    '',
    'Edit PARAMETERS and MODEL, then either:',
    '  * run `python <this file>` to write model.step, or',
    "  * send it back with llull's import_code tool: parameters, expressions and",
    '    feature order are rebuilt as an editable llull feature history.',
    'Raw library code is welcome too: wrap a shape with custom(shape) to include it.',
    '"""',
  ].join('\n');
}

/** Emit a runnable CadQuery or build123d script for the program. */
export function emitPython(program: FeatureProgram, backend: PythonBackend): string {
  const lines: string[] = [header(program, backend), ''];
  lines.push(`LLULL_UNITS = ${quote(program.units)}`, '');
  lines.push(`# ── llull runtime (${LIBRARY[backend]}) · keep unchanged ${'─'.repeat(30)}`);
  lines.push(pythonRuntime(backend));
  lines.push(`# ── PARAMETERS ${'─'.repeat(50)}`);
  if (program.parameters.length === 0) lines.push('# (none)');
  for (const p of program.parameters) {
    lines.push(
      `${p.identifier} = param(${quote(p.name)}, ${p.expression ?? formatNumber(p.value)})`,
    );
  }
  lines.push('', `# ── MODEL ${'─'.repeat(55)}`);
  program.features.forEach((feature, i) => {
    const heading = stepHeading(feature, program.features[i - 1]);
    if (heading !== null) lines.push(`# ${heading}`);
    lines.push(featureLine(feature));
  });
  lines.push(
    '',
    'result = finish()',
    '',
    'if __name__ == "__main__":',
    '    export_step(result, "model.step")',
    'elif "show_object" in globals():',
    '    show_object(result)  # noqa: F821 (CQ-editor)',
    '',
  );
  return lines.join('\n');
}
