/**
 * Building (AEC / BIM) model — the CONSTRUCTIVE definition of a building (architecture L8).
 *
 * @layer core/model
 * @invariant every element's evaluated geometry lives in `CadDocument.entities` under the ids
 *            listed in `entityIds`; it is regenerated by building commands, never edited directly.
 * @see docs/CONSTRUCTION.md, src/core/building/evaluate.ts
 */

import type { Vec2, Vec3 } from './types';

/** Building element categories (Revit/IFC-like). */
export type BimCategory =
  | 'grid'
  | 'wall'
  | 'door'
  | 'window'
  | 'slab'
  | 'column'
  | 'beam'
  | 'stair'
  | 'room'
  | 'member'
  | 'footing'
  | 'panel'
  | 'equipment'
  | 'pipe'
  | 'tray'
  | 'plate'
  | 'curvedWall';

/** A building storey. `elevation` is the finished-floor height; `height` is floor-to-floor. */
export interface BuildingLevel {
  readonly id: string;
  name: string;
  elevation: number;
  height: number;
}

/** Title-block / IFC project metadata. All free text. */
export interface ProjectInfo {
  name: string;
  client: string;
  address: string;
  author: string;
  drawingNumber: string;
  revision: string;
  date: string;
}

interface ElementBase {
  readonly id: string;
  readonly category: BimCategory;
  /** Human-facing tag shown in schedules and plans, e.g. "W3", "D01", "A", "101". */
  mark: string;
  /** Ids of the evaluated entities generated for this element. */
  entityIds: string[];
}

/** A structural grid axis (not level-bound). `mark` is the bubble label. */
export interface GridElement extends ElementBase {
  readonly category: 'grid';
  start: Vec2;
  end: Vec2;
}

/** A straight wall. `start`/`end` are the plan centerline; height is measured from the level + baseOffset. */
export type WallLayerFunction = 'structure' | 'insulation' | 'membrane' | 'air' | 'finish';

/** One layer of a wall build-up. */
export interface WallLayer {
  material: string;
  thickness: number;
  function: WallLayerFunction;
}

export interface WallElement extends ElementBase {
  readonly category: 'wall';
  levelId: string;
  start: Vec2;
  end: Vec2;
  /** Equals the sum of `layers` thicknesses when a build-up is set. */
  thickness: number;
  height: number;
  baseOffset: number;
  /** Structural material (the build-up's first structure layer when layers are set). */
  material: string;
  /** Build-up from the right-hand face (looking from start to end) to the left-hand face. */
  layers?: WallLayer[];
}

/** A door or window hosted by a wall. `offset` = distance along the wall from its start to the opening center. */
export interface OpeningElement extends ElementBase {
  readonly category: 'door' | 'window';
  hostId: string;
  offset: number;
  width: number;
  height: number;
  sillHeight: number;
  /** Door hinge side seen from the wall start looking to the end. Ignored for windows. */
  swing: 'left' | 'right';
  material: string;
}

export type SlabRole = 'floor' | 'roof' | 'foundation';

/** A horizontal slab. Its TOP face sits at level elevation + `offset`. */
export interface SlabElement extends ElementBase {
  readonly category: 'slab';
  levelId: string;
  boundary: Vec2[];
  thickness: number;
  offset: number;
  role: SlabRole;
  material: string;
  /** Voids through the slab (stair wells, shafts), as plan polygons inside the boundary. */
  openings?: Vec2[][];
}

/** A vertical column standing on its level. */
export interface ColumnElement extends ElementBase {
  readonly category: 'column';
  levelId: string;
  location: Vec2;
  shape: 'rectangular' | 'circular';
  /** Width (or diameter for circular). */
  width: number;
  depth: number;
  height: number;
  material: string;
}

/** A horizontal beam. Its TOP face sits at level elevation + level height + `topOffset`. */
export interface BeamElement extends ElementBase {
  readonly category: 'beam';
  levelId: string;
  start: Vec2;
  end: Vec2;
  width: number;
  depth: number;
  topOffset: number;
  material: string;
}

/** A straight-run stair rising from its level. `angle` is the run direction (radians, CCW from +X). */
export interface StairElement extends ElementBase {
  readonly category: 'stair';
  levelId: string;
  start: Vec2;
  angle: number;
  width: number;
  riserCount: number;
  riserHeight: number;
  treadDepth: number;
  material: string;
}

/** A room / space. `mark` is the room number. */
export interface RoomElement extends ElementBase {
  readonly category: 'room';
  levelId: string;
  name: string;
  boundary: Vec2[];
}

/** Structural role of a steel member (drives layer, mark prefix and IFC class). */
export type MemberRole = 'column' | 'rafter' | 'beam' | 'brace' | 'purlin' | 'rail' | 'crane';

/**
 * A steel member: a catalogue section swept from `start` to `end` (z relative to the level).
 * `roll` rotates the section about its axis (radians).
 */
export interface SteelMemberElement extends ElementBase {
  readonly category: 'member';
  levelId: string;
  role: MemberRole;
  profile: string;
  start: Vec3;
  end: Vec3;
  roll: number;
  material: string;
  /** Free note carried to schedules, e.g. "Crane 10 t, hook 6.5 m". */
  note?: string;
}

/** A concrete pad footing; its TOP sits at level elevation + `topOffset` (usually negative). */
export interface FootingElement extends ElementBase {
  readonly category: 'footing';
  levelId: string;
  location: Vec2;
  width: number;
  length: number;
  thickness: number;
  topOffset: number;
  material: string;
}

/** A planar cladding / roofing / sandwich panel through 3D `corners` (z relative to the level). */
export interface PanelElement extends ElementBase {
  readonly category: 'panel';
  levelId: string;
  role: 'roof' | 'wall';
  corners: Vec3[];
  thickness: number;
  material: string;
}

/** A machine / process equipment footprint with its maintenance clearance zone. */
export interface EquipmentElement extends ElementBase {
  readonly category: 'equipment';
  levelId: string;
  name: string;
  location: Vec2;
  /** Plan rotation (radians). */
  angle: number;
  /** [length along its x, width along its y, height]. */
  size: Vec3;
  /** Free space required around the footprint for operation / maintenance. */
  clearance: number;
  /** Operating weight in kg (0 when unknown). */
  weight: number;
}

/** A pipe run through 3D points (z relative to the level). */
export interface PipeElement extends ElementBase {
  readonly category: 'pipe';
  levelId: string;
  points: Vec3[];
  diameter: number;
  /** Fluid / service, e.g. "compressed air", "cooling water". */
  service: string;
  material: string;
}

/** A cable tray run through 3D points (z = tray centre, relative to the level). */
export interface CableTrayElement extends ElementBase {
  readonly category: 'tray';
  levelId: string;
  points: Vec3[];
  width: number;
  /** Side height of the U section. */
  height: number;
  /** Cable system, e.g. "power", "data", "instrumentation". */
  system: string;
}

/** A steel base plate with anchor bolts under the foot of a steel column (follows the column). */
export interface BasePlateElement extends ElementBase {
  readonly category: 'plate';
  levelId: string;
  /** The steel column (member) it carries. */
  memberId: string;
  /** Plate size along the column depth. */
  length: number;
  /** Plate size along the column width. */
  width: number;
  thickness: number;
  /** Anchor bolts: an even number, in two rows along the length. */
  boltCount: number;
  boltDiameter: number;
  material: string;
}

/** A curved wall: centreline arc from `start` through `through` to `end` (plan). */
export interface CurvedWallElement extends ElementBase {
  readonly category: 'curvedWall';
  levelId: string;
  start: Vec2;
  through: Vec2;
  end: Vec2;
  thickness: number;
  height: number;
  baseOffset: number;
  material: string;
}

export type BuildingElement =
  | GridElement
  | WallElement
  | OpeningElement
  | SlabElement
  | ColumnElement
  | BeamElement
  | StairElement
  | RoomElement
  | SteelMemberElement
  | FootingElement
  | PanelElement
  | EquipmentElement
  | PipeElement
  | CableTrayElement
  | BasePlateElement
  | CurvedWallElement;

export interface BuildingModel {
  /** Stable unique id of this building; salts IFC GlobalIds so separate projects never collide. */
  uid?: string;
  /** Highest number ever issued per id prefix ("wall", "level", …), so deleted ids are never reused. */
  counters?: Record<string, number>;
  project: ProjectInfo;
  levels: Record<string, BuildingLevel>;
  /** Levels sorted by ascending elevation. */
  levelOrder: string[];
  /** Level new elements go to when no levelId is given. */
  activeLevelId: string | null;
  elements: Record<string, BuildingElement>;
  elementOrder: string[];
  /** Unit rates keyed by takeoff line key ("wall.concrete.m3", "door.*.ea", …); used by estimate_cost. */
  costRates?: Record<string, number>;
  /** ISO currency code for cost estimates, e.g. "EUR". */
  currency?: string;
}

export function createEmptyBuilding(): BuildingModel {
  return {
    project: {
      name: 'Untitled project',
      client: '',
      address: '',
      author: '',
      drawingNumber: 'A-101',
      revision: '0',
      date: '',
    },
    levels: {},
    levelOrder: [],
    activeLevelId: null,
    elements: {},
    elementOrder: [],
  };
}
