/**
 * Building (AEC / BIM) model — the CONSTRUCTIVE definition of a building (architecture L8).
 *
 * @layer core/model
 * @invariant every element's evaluated geometry lives in `CadDocument.entities` under the ids
 *            listed in `entityIds`; it is regenerated by building commands, never edited directly.
 * @see docs/CONSTRUCTION.md, src/core/building/evaluate.ts
 */

import type { Vec2 } from './types';

/** Building element categories (Revit/IFC-like). */
export type BimCategory =
  | 'grid'
  | 'wall'
  | 'door'
  | 'window'
  | 'slab'
  | 'column'
  | 'beam'
  | 'stair'
  | 'room';

/** A building storey. `elevation` is the finished-floor height; `height` is floor-to-floor. */
export interface BuildingLevel {
  readonly id: string;
  name: string;
  elevation: number;
  height: number;
}

/** Title-block / IFC project metadata. All free text. */
export interface ProjectInfo {
  name: string;
  client: string;
  address: string;
  author: string;
  drawingNumber: string;
  revision: string;
  date: string;
}

interface ElementBase {
  readonly id: string;
  readonly category: BimCategory;
  /** Human-facing tag shown in schedules and plans, e.g. "W3", "D01", "A", "101". */
  mark: string;
  /** Ids of the evaluated entities generated for this element. */
  entityIds: string[];
}

/** A structural grid axis (not level-bound). `mark` is the bubble label. */
export interface GridElement extends ElementBase {
  readonly category: 'grid';
  start: Vec2;
  end: Vec2;
}

/** A straight wall. `start`/`end` are the plan centerline; height is measured from the level + baseOffset. */
export interface WallElement extends ElementBase {
  readonly category: 'wall';
  levelId: string;
  start: Vec2;
  end: Vec2;
  thickness: number;
  height: number;
  baseOffset: number;
  material: string;
}

/** A door or window hosted by a wall. `offset` = distance along the wall from its start to the opening center. */
export interface OpeningElement extends ElementBase {
  readonly category: 'door' | 'window';
  hostId: string;
  offset: number;
  width: number;
  height: number;
  sillHeight: number;
  /** Door hinge side seen from the wall start looking to the end. Ignored for windows. */
  swing: 'left' | 'right';
  material: string;
}

export type SlabRole = 'floor' | 'roof' | 'foundation';

/** A horizontal slab. Its TOP face sits at level elevation + `offset`. */
export interface SlabElement extends ElementBase {
  readonly category: 'slab';
  levelId: string;
  boundary: Vec2[];
  thickness: number;
  offset: number;
  role: SlabRole;
  material: string;
  /** Voids through the slab (stair wells, shafts), as plan polygons inside the boundary. */
  openings?: Vec2[][];
}

/** A vertical column standing on its level. */
export interface ColumnElement extends ElementBase {
  readonly category: 'column';
  levelId: string;
  location: Vec2;
  shape: 'rectangular' | 'circular';
  /** Width (or diameter for circular). */
  width: number;
  depth: number;
  height: number;
  material: string;
}

/** A horizontal beam. Its TOP face sits at level elevation + level height + `topOffset`. */
export interface BeamElement extends ElementBase {
  readonly category: 'beam';
  levelId: string;
  start: Vec2;
  end: Vec2;
  width: number;
  depth: number;
  topOffset: number;
  material: string;
}

/** A straight-run stair rising from its level. `angle` is the run direction (radians, CCW from +X). */
export interface StairElement extends ElementBase {
  readonly category: 'stair';
  levelId: string;
  start: Vec2;
  angle: number;
  width: number;
  riserCount: number;
  riserHeight: number;
  treadDepth: number;
  material: string;
}

/** A room / space. `mark` is the room number. */
export interface RoomElement extends ElementBase {
  readonly category: 'room';
  levelId: string;
  name: string;
  boundary: Vec2[];
}

export type BuildingElement =
  | GridElement
  | WallElement
  | OpeningElement
  | SlabElement
  | ColumnElement
  | BeamElement
  | StairElement
  | RoomElement;

export interface BuildingModel {
  project: ProjectInfo;
  levels: Record<string, BuildingLevel>;
  /** Levels sorted by ascending elevation. */
  levelOrder: string[];
  /** Level new elements go to when no levelId is given. */
  activeLevelId: string | null;
  elements: Record<string, BuildingElement>;
  elementOrder: string[];
  /** Unit rates keyed by takeoff line key ("wall.concrete.m3", "door.*.ea", …); used by estimate_cost. */
  costRates?: Record<string, number>;
  /** ISO currency code for cost estimates, e.g. "EUR". */
  currency?: string;
}

export function createEmptyBuilding(): BuildingModel {
  return {
    project: {
      name: 'Untitled project',
      client: '',
      address: '',
      author: '',
      drawingNumber: 'A-101',
      revision: '0',
      date: '',
    },
    levels: {},
    levelOrder: [],
    activeLevelId: null,
    elements: {},
    elementOrder: [],
  };
}
