import { describe, expect, it } from 'vitest';
import { execute } from '@core/commands/registry';
import { deserializeDocument, serializeDocument } from '@core/commands/persistence';
import { createEmptyDocument, type CadDocument } from '@core/model/types';

const SQUARE = [
  [0, 0],
  [6000, 0],
  [6000, 5000],
  [0, 5000],
];

type Step = [name: string, params: Record<string, unknown>];

const STEPS: Step[] = [
  ['add_level', { name: 'Ground', height: 4000 }],
  ['draw_walls', { points: SQUARE, closed: true, thickness: 200 }],
  ['add_door', { wallId: 'wall-1', offset: 1500 }],
  ['add_window', { wallId: 'wall-2', offset: 2500 }],
  ['add_curved_wall', { start: [7000, 0], through: [8000, 1000], end: [9000, 0], thickness: 200 }],
  ['add_slab', { wallIds: ['wall-1', 'wall-2', 'wall-3', 'wall-4'] }],
  [
    'add_slab_opening',
    {
      slabId: 'slab-1',
      boundary: [
        [1000, 1000],
        [2000, 1000],
        [2000, 2000],
        [1000, 2000],
      ],
    },
  ],
  ['add_column', { location: [3000, 2500] }],
  ['add_beam', { start: [0, 2500], end: [6000, 2500] }],
  ['add_stair', { start: [4000, 500], angle: 0 }],
  ['add_room', { name: 'Hall', wallIds: ['wall-1', 'wall-2', 'wall-3', 'wall-4'] }],
  [
    'add_steel_member',
    { profile: 'HEA300', role: 'column', start: [0, 8000, 0], end: [0, 8000, 5000] },
  ],
  [
    'add_steel_member',
    { profile: 'HEA300', role: 'column', start: [6000, 8000, 0], end: [6000, 8000, 5000] },
  ],
  [
    'add_steel_member',
    { profile: 'IPE400', role: 'beam', start: [0, 8000, 5000], end: [6000, 8000, 5000] },
  ],
  ['add_base_plates', {}],
  ['add_footing', { underColumns: true }],
  ['add_equipment', { name: 'Pump', mark: 'P-1', location: [3000, 9500], size: [1500, 800, 900] }],
  [
    'add_pipe_run',
    {
      points: [
        [0, 9500, 1000],
        [3000, 9500, 1000],
        [3000, 9500, 4000],
      ],
      dn: 100,
    },
  ],
  [
    'add_cable_tray',
    {
      points: [
        [0, 7000, 3000],
        [6000, 7000, 3000],
      ],
    },
  ],
];

function build(): CadDocument {
  let doc = createEmptyDocument();
  for (const [name, params] of STEPS) {
    const result = execute(doc, name, params);
    expect(result.affected.length, `${name}: ${result.summary}`).toBeGreaterThan(0);
    doc = result.document;
  }
  return doc;
}

const roundTrip = (doc: CadDocument): CadDocument => deserializeDocument(serializeDocument(doc));

describe('derivation guard on every generated entity kind', () => {
  it('rejects move, rotate, scale, mirror and delete of any generated entity', () => {
    const doc = build();
    const generated = Object.values(doc.building?.elements ?? {}).flatMap(
      (element) => element.entityIds,
    );
    const categories = new Set(Object.values(doc.building?.elements ?? {}).map((e) => e.category));
    expect(categories.size).toBeGreaterThanOrEqual(15);
    expect(generated.length).toBeGreaterThan(50);
    const attempts: Array<(id: string) => [string, Record<string, unknown>]> = [
      (id) => ['move_entity', { id, delta: [10, 0, 0] }],
      (id) => ['rotate_entity', { id, delta: [0, 0, 0.1] }],
      (id) => ['scale_entity', { id, factor: 2 }],
      (id) => ['mirror_entity', { id, axis: 'x' }],
      (id) => ['delete_entity', { id }],
    ];
    for (const id of generated) {
      for (const attempt of attempts) {
        const [name, params] = attempt(id);
        const result = execute(doc, name, params);
        const label = `${name} ${id}: ${result.summary}`;
        if (/rejected: it would edit geometry generated by building/.test(result.summary)) {
          expect(result.document, label).toBe(doc);
        } else {
          // A mirror across an axis the entity already sits on changes nothing: no violation.
          expect(JSON.stringify(result.document.entities), label).toBe(
            JSON.stringify(doc.entities),
          );
          expect(name, label).toBe('mirror_entity');
        }
      }
    }
  });
});

describe('save -> load round trip of derived building geometry', () => {
  it('restores every derived entity of a mixed model exactly', () => {
    const doc = build();
    expect(Object.keys(doc.building?.elements ?? {}).length).toBeGreaterThan(20);
    const loaded = roundTrip(doc);
    expect(loaded.entities).toEqual(doc.entities);
    expect(loaded.order).toEqual(doc.order);
    expect(loaded.building).toEqual(doc.building);
    expect(loaded.layers).toEqual(doc.layers);
  });

  it('still restores identically after update, move and delete edits', () => {
    let doc = build();
    const edits: Step[] = [
      ['update_wall', { wallId: 'wall-3', thickness: 250 }],
      ['update_opening', { openingId: 'door-1', width: 1000 }],
      ['move_building_element', { elementIds: ['column-1'], delta: [200, 0] }],
      ['update_level', { levelId: 'level-1', height: 4200 }],
      ['delete_building_element', { elementIds: ['room-1'] }],
    ];
    for (const [name, params] of edits) {
      const result = execute(doc, name, params);
      expect(result.affected.length, `${name}: ${result.summary}`).toBeGreaterThan(0);
      doc = result.document;
    }
    const loaded = roundTrip(doc);
    expect(loaded.entities).toEqual(doc.entities);
    expect(loaded.order).toEqual(doc.order);
  });
});
