/**
 * Building (AEC / BIM) model — the CONSTRUCTIVE definition of a building (architecture L8).
 *
 * @layer core/model
 * @invariant every element's evaluated geometry lives in `CadDocument.entities` under the ids
 *            listed in `entityIds`; it is regenerated by building commands, never edited directly.
 * @see docs/CONSTRUCTION.md, packages/domain-aec/src/evaluate.ts
 */

import type { Vec2, Vec3 } from './types';

/** Building element categories (Revit/IFC-like). */
export type BimCategory =
  | 'grid'
  | 'wall'
  | 'door'
  | 'window'
  | 'slab'
  | 'column'
  | 'beam'
  | 'stair'
  | 'room'
  | 'member'
  | 'footing'
  | 'panel'
  | 'equipment'
  | 'pipe'
  | 'tray'
  | 'plate'
  | 'curvedWall'
  | 'connection'
  | 'pipeSupport';

/** A building storey. `elevation` is the finished-floor height; `height` is floor-to-floor. */
export interface BuildingLevel {
  readonly id: string;
  name: string;
  elevation: number;
  height: number;
}

/** Title-block / IFC project metadata. All free text. */
export interface ProjectInfo {
  name: string;
  client: string;
  address: string;
  author: string;
  drawingNumber: string;
  revision: string;
  date: string;
}

interface ElementBase {
  readonly id: string;
  readonly category: BimCategory;
  /** Human-facing tag shown in schedules and plans, e.g. "W3", "D01", "A", "101". */
  mark: string;
  /** Ids of the evaluated entities generated for this element. */
  entityIds: string[];
}

interface LevelElementBase extends ElementBase {
  levelId: string;
}

/** A structural grid axis (not level-bound). `mark` is the bubble label. */
export interface GridElement extends ElementBase {
  readonly category: 'grid';
  start: Vec2;
  end: Vec2;
}

export type WallLayerFunction = 'structure' | 'insulation' | 'membrane' | 'air' | 'finish';

/** One layer of a wall build-up. */
export interface WallLayer {
  material: string;
  thickness: number;
  function: WallLayerFunction;
}

/** A straight wall. `start`/`end` are the plan centerline; height is measured from the level + baseOffset. */
export interface WallElement extends LevelElementBase {
  readonly category: 'wall';
  start: Vec2;
  end: Vec2;
  /** Equals the sum of `layers` thicknesses when a build-up is set. */
  thickness: number;
  height: number;
  baseOffset: number;
  /** Structural material (the build-up's first structure layer when layers are set). */
  material: string;
  /** Build-up from the right-hand face (looking from start to end) to the left-hand face. */
  layers?: WallLayer[];
}

/** A door or window hosted by a wall. `offset` = distance along the wall from its start to the opening center. */
export interface OpeningElement extends ElementBase {
  readonly category: 'door' | 'window';
  hostId: string;
  offset: number;
  width: number;
  height: number;
  sillHeight: number;
  /** Door hinge side seen from the wall start looking to the end. Ignored for windows. */
  swing: 'left' | 'right';
  material: string;
}

type SlabRole = 'floor' | 'roof' | 'foundation';

/** A horizontal slab. Its TOP face sits at level elevation + `offset`. */
export interface SlabElement extends LevelElementBase {
  readonly category: 'slab';
  boundary: Vec2[];
  thickness: number;
  offset: number;
  role: SlabRole;
  material: string;
  /** Voids through the slab (stair wells, shafts), as plan polygons inside the boundary. */
  openings?: Vec2[][];
}

/** A vertical column standing on its level. */
export interface ColumnElement extends LevelElementBase {
  readonly category: 'column';
  location: Vec2;
  shape: 'rectangular' | 'circular';
  /** Width (or diameter for circular). */
  width: number;
  depth: number;
  height: number;
  material: string;
}

/** A horizontal beam. Its TOP face sits at level elevation + level height + `topOffset`. */
export interface BeamElement extends LevelElementBase {
  readonly category: 'beam';
  start: Vec2;
  end: Vec2;
  width: number;
  depth: number;
  topOffset: number;
  material: string;
}

/** A straight-run stair rising from its level. `angle` is the run direction (radians, CCW from +X). */
export interface StairElement extends LevelElementBase {
  readonly category: 'stair';
  start: Vec2;
  angle: number;
  width: number;
  riserCount: number;
  riserHeight: number;
  treadDepth: number;
  material: string;
}

/** A room / space. `mark` is the room number. */
export interface RoomElement extends LevelElementBase {
  readonly category: 'room';
  name: string;
  boundary: Vec2[];
}

/** Structural role of a steel member (drives layer, mark prefix and IFC class). */
export type MemberRole = 'column' | 'rafter' | 'beam' | 'brace' | 'purlin' | 'rail' | 'crane';

/** End connection of a beam to the column it frames into: moment-transmitting or not. */
export type JointFixity = 'pinned' | 'rigid';

/** Column base: free to rotate, or restraining the column foot rotation. */
export type BaseFixity = 'pinned' | 'fixed';

/**
 * A steel member: a catalogue section swept from `start` to `end` (z relative to the level).
 * `roll` rotates the section about its axis (radians).
 */
export interface SteelMemberElement extends LevelElementBase {
  readonly category: 'member';
  role: MemberRole;
  profile: string;
  start: Vec3;
  end: Vec3;
  roll: number;
  material: string;
  /** Free note carried to schedules, e.g. "Crane 10 t, hook 6.5 m". */
  note?: string;
  /** Beams: joint at `start` / `end`; absent = pinned. 'rigid' makes the beam a moment-frame member. */
  startJoint?: JointFixity;
  endJoint?: JointFixity;
  /** Columns: base fixity in check_steel_members; absent = the base plate's fixity, else pinned. */
  baseFixity?: BaseFixity;
}

/** A concrete pad footing; its TOP sits at level elevation + `topOffset` (usually negative). */
export interface FootingElement extends LevelElementBase {
  readonly category: 'footing';
  location: Vec2;
  width: number;
  length: number;
  thickness: number;
  topOffset: number;
  material: string;
  /** Bottom mat (same bars both ways), set by design_footings; document units. */
  reinforcement?: { barDiameter: number; spacing: number; cover: number };
}

/** A planar cladding / roofing / sandwich panel through 3D `corners` (z relative to the level). */
export interface PanelElement extends LevelElementBase {
  readonly category: 'panel';
  role: 'roof' | 'wall';
  corners: Vec3[];
  thickness: number;
  material: string;
}

export type EquipmentShape = 'box' | 'vertical_vessel' | 'horizontal_vessel';

/** A machine / process equipment footprint with its maintenance clearance zone. */
export interface EquipmentElement extends LevelElementBase {
  readonly category: 'equipment';
  name: string;
  location: Vec2;
  /** Plan rotation (radians). */
  angle: number;
  /** [length along its x, width along its y, height]; always the bounding box (vessels: normalised). */
  size: Vec3;
  /** Absent = box. Vessels are cylinders inscribed in `size`. */
  shape?: EquipmentShape;
  /** Free space required around the footprint for operation / maintenance. */
  clearance: number;
  /** Operating weight in kg (0 when unknown). */
  weight: number;
}

/** A pipe run through 3D points (z relative to the level). */
export interface PipeElement extends LevelElementBase {
  readonly category: 'pipe';
  points: Vec3[];
  diameter: number;
  /** Fluid / service, e.g. "compressed air", "cooling water". */
  service: string;
  material: string;
  /** Line number, e.g. "L-101" (line list). */
  line?: string;
  /** Nominal size (DN, integer), e.g. 100. */
  dn?: number;
  /** Origin: equipment tag or battery-limit / tie-in id. */
  from?: string;
  /** Destination: equipment tag or battery-limit / tie-in id. */
  to?: string;
}

export type PipeSupportType = 'shoe' | 'hanger' | 'guide' | 'anchor';

/**
 * A support on a pipe: shoe / guide / anchor rest on steel below, a hanger hangs by a rod from
 * steel above; on a riser (steep segment) a shoe / guide / anchor is a clamp with a bracket to the
 * steel beside the pipe (`standoff`). Hosted by its pipe (moves, copies and is deleted with it).
 */
export interface PipeSupportElement extends LevelElementBase {
  readonly category: 'pipeSupport';
  /** The pipe it carries. */
  pipeId: string;
  type: PipeSupportType;
  /** Point on the pipe centreline: plan x / y, z relative to the level (like pipe points). */
  position: Vec3;
  /** Steel member it bears on (below for shoe / guide / anchor, above for a hanger); null = unattached. */
  memberId: string | null;
  /** Hanger rod length, pipe top to the member underside (0 for other types and unattached hangers). */
  rodLength: number;
  /** Shoe / guide / anchor block height, pipe underside down to the member top (0 for hangers). */
  pedestalHeight: number;
  /** Riser supports only: horizontal gap from the pipe surface to the member face (bracket length). */
  standoff?: number;
  /** Riser supports only: plan direction from the pipe toward the member, radians. */
  standoffAngle?: number;
}

/** A cable tray run through 3D points (z = tray centre, relative to the level). */
export interface CableTrayElement extends LevelElementBase {
  readonly category: 'tray';
  points: Vec3[];
  width: number;
  /** Side height of the U section. */
  height: number;
  /** Cable system, e.g. "power", "data", "instrumentation". */
  system: string;
}

/** A steel base plate with anchor bolts under the foot of a steel column (follows the column). */
export interface BasePlateElement extends LevelElementBase {
  readonly category: 'plate';
  /** The steel column (member) it carries. */
  memberId: string;
  /** Plate size along the column depth. */
  length: number;
  /** Plate size along the column width. */
  width: number;
  thickness: number;
  /** Anchor bolts: an even number, in two rows along the length. */
  boltCount: number;
  boltDiameter: number;
  material: string;
  /** Base fixity of the column in the frame analysis; absent = pinned. */
  fixity?: 'pinned' | 'fixed';
}

/** A curved wall: centreline arc from `start` through `through` to `end` (plan). */
export interface CurvedWallElement extends LevelElementBase {
  readonly category: 'curvedWall';
  start: Vec2;
  through: Vec2;
  end: Vec2;
  thickness: number;
  height: number;
  baseOffset: number;
  material: string;
}

/**
 * A bolted end-plate moment connection of a portal frame: at the eaves (rafter → column, with a
 * haunch under the rafter) or the apex (rafter → rafter). Geometry follows the rafter.
 */
export interface MomentConnectionElement extends LevelElementBase {
  readonly category: 'connection';
  kind: 'eaves' | 'apex';
  /** The rafter whose end is connected (host). */
  rafterId: string;
  /** Which end of the rafter. */
  end: 'start' | 'end';
  /** The column (eaves) or the other rafter (apex). */
  otherId: string;
  plateThickness: number;
  /** Bolt rows (two bolts per row). */
  boltRows: number;
  boltDiameter: number;
  /** Haunch length along the rafter (0 = none). */
  haunchLength: number;
  material: string;
}

export type BuildingElement =
  | GridElement
  | WallElement
  | OpeningElement
  | SlabElement
  | ColumnElement
  | BeamElement
  | StairElement
  | RoomElement
  | SteelMemberElement
  | FootingElement
  | PanelElement
  | EquipmentElement
  | PipeElement
  | CableTrayElement
  | BasePlateElement
  | CurvedWallElement
  | MomentConnectionElement
  | PipeSupportElement;

export interface BuildingModel {
  /** Stable unique id of this building; salts IFC GlobalIds so separate projects never collide. */
  uid?: string;
  /** Highest number ever issued per id prefix ("wall", "level", …), so deleted ids are never reused. */
  counters?: Record<string, number>;
  project: ProjectInfo;
  levels: Record<string, BuildingLevel>;
  /** Levels sorted by ascending elevation. */
  levelOrder: string[];
  /** Level new elements go to when no levelId is given. */
  activeLevelId: string | null;
  elements: Record<string, BuildingElement>;
  elementOrder: string[];
  /** Unit rates keyed by takeoff line key ("wall.concrete.m3", "door.*.ea", …); used by estimate_cost. */
  costRates?: Record<string, number>;
  /** ISO currency code for cost estimates, e.g. "EUR". */
  currency?: string;
}

export function createEmptyBuilding(): BuildingModel {
  return {
    project: {
      name: 'Untitled project',
      client: '',
      address: '',
      author: '',
      drawingNumber: 'A-101',
      revision: '0',
      date: '',
    },
    levels: {},
    levelOrder: [],
    activeLevelId: null,
    elements: {},
    elementOrder: [],
  };
}
