/**
 * Building derivation guard: entities generated by building elements change only through
 * building commands (MG4.5).
 * @layer core/commands/building
 * @pure
 */

import type { DerivationGuard } from '../derivation';
import { editedBuildingElements } from './integrity';

export const buildingDerivationGuard: DerivationGuard = {
  domain: 'building',
  check(previous, next) {
    const edited = editedBuildingElements(previous, next);
    if (edited.length === 0) return null;
    return (
      `it would edit geometry generated by building element(s) ${edited.join(', ')}. ` +
      'Edit the element instead (update_wall, update_opening, update_level, move_building_element, delete_building_element, …).'
    );
  },
};
