/** Derivation guards: derived geometry is read-only; edit its source. */
import { describe, it, expect } from 'vitest';
import { createEmptyDocument } from '@core/model/types';
import { execute } from '@core/commands/registry';
import { type DerivationGuard, derivationViolation } from '@core/commands/derivation';

const alwaysRejects: DerivationGuard = { domain: 'test', check: () => 'nope.' };
const alwaysAllows: DerivationGuard = { domain: 'ok', check: () => null };

describe('derivationViolation', () => {
  it('formats the first violation and skips identical documents', () => {
    const before = createEmptyDocument();
    const after = { ...before, units: 'm' as const };
    expect(derivationViolation([alwaysAllows, alwaysRejects], 'x_cmd', before, after)).toBe(
      'x_cmd rejected: nope.',
    );
    expect(derivationViolation([alwaysRejects], 'x_cmd', before, before)).toBeNull();
    expect(derivationViolation([alwaysAllows], 'x_cmd', before, after)).toBeNull();
  });

  it('execute rejects a direct edit of building-generated geometry', () => {
    const doc = execute(createEmptyDocument(), 'add_wall', {
      start: [0, 0],
      end: [5000, 0],
    }).document;
    const generatedId = doc.order[0] ?? '';
    const moved = execute(doc, 'move_entity', { id: generatedId, delta: [10, 0, 0] });
    expect(moved.document).toBe(doc);
    expect(moved.summary).toMatch(
      /^move_entity rejected: it would edit geometry generated by building element\(s\) wall-1/,
    );
  });
});
