/**
 * Feature history commands — named, replayable command list (architecture L8).
 *
 * These meta-commands edit the `featureHistory` list and regenerate the
 * document by replaying all non-suppressed steps from `createEmptyDocument()`.
 *
 * IMPORTANT: meta-commands must NOT themselves append a FeatureStep; they carry
 * `annotations.metaHistory: true` so `execute()` skips the append hook for them.
 *
 * Replays resolve commands through the active `ExecutionContext.registry`.
 *
 * @layer core/commands
 */

import type { CadDocument, FeatureStep } from '../model/types';
import { createEmptyDocument } from '../model/types';
import { createEmptyBuilding } from '../model/building';
import { currentContext } from './context';
import type { CommandDefinition, CommandResult } from './types';
import { defineCommand, z } from './schema';
import { orphanState } from './history_carry';
import { kernelRefusal } from './kernelRefusal';
import { nextStateKey } from './replayCache';
import { hashText } from '../lib/hash';
import { remapIds } from './regenerate';
import { resolveStepForReplay, runReplayStep } from './replayStep';

// ---------------------------------------------------------------------------
// Internal replay helper
// ---------------------------------------------------------------------------

/** One successfully replayed step, reported to `replayHistory`'s optional `onStep` observer. */
export interface ReplayStepEvent {
  readonly step: FeatureStep;
  /** Recorded params with ids remapped but `=expr` strings kept. */
  readonly rawParams: unknown;
  /** Params actually passed to the command (`=expr` resolved, ids remapped). */
  readonly params: unknown;
  readonly before: CadDocument;
  readonly after: CadDocument;
}

/**
 * Replay all non-suppressed steps in `history` from a fresh document,
 * preserving document-level state from `base` (classification in history_carry.ts).
 *
 * Steps referencing unknown command names are silently skipped (graceful
 * degradation — the command may have been renamed or removed).
 *
 * Steps whose `run` throws are silently skipped (e.g. a move referencing
 * an entity that a prior suppressed step would have created).
 *
 * Any `=expr` strings in step params are resolved against `base.parameters`
 * before each step runs. Unresolved expressions are reported in `resolveWarnings`.
 *
 * @pure — returns a new CadDocument; never mutates `base`.
 * @failure a live step needs the geometry kernel (`requiresKernel`) and none is available ->
 *   returns `base` unchanged (+ a warning) instead of regenerating without that step's geometry
 */
export function replayHistory(
  base: CadDocument,
  history: FeatureStep[],
  getCommandFn: (name: string) => CommandDefinition<unknown> | undefined,
  resolveWarnings?: string[],
  onStep?: (event: ReplayStepEvent) => void,
): CadDocument {
  const context = currentContext();
  const refusal = kernelRefusal(base, history, getCommandFn);
  if (refusal !== null) {
    resolveWarnings?.push(`replay refused: ${refusal}`);
    return base;
  }
  // Start from empty geometry but preserve document-level settings.
  let doc: CadDocument = {
    ...createEmptyDocument(),
    camera: base.camera,
    units: base.units,
    displayPrecision: base.displayPrecision,
    parameters: base.parameters,
    animations: base.animations,
    groups: base.groups,
    layers: base.layers,
    layerOrder: base.layerOrder,
    featureHistory: history,
    ...(base.nextStepNumber !== undefined ? { nextStepNumber: base.nextStepNumber } : {}),
    // Recipes must survive replay so that a recorded `instantiate_recipe` step can
    // re-expand its recipe when this history is replayed again (e.g. via replay_history).
    recipes: base.recipes,
    configurations: base.configurations,
    // Materials/components/constraints/joints/drives are regenerated by their recorded steps;
    // only entries no step produced are carried (see history_carry.ts).
    ...orphanState(base),
    // The building identity (IFC GlobalId salt) survives replay; its content is regenerated.
    ...(base.building?.uid !== undefined
      ? { building: { ...createEmptyBuilding(), uid: base.building.uid } }
      : {}),
  };

  // idMap tracks old entity id (from when the step was first recorded) → new id
  // (assigned during this replay). Subsequent steps' params are rewritten via
  // remapIds. Step-scoped ids replay identically, so this only maps legacy (pre-v2) ids.
  let idMap = new Map<string, string>();
  const cache = context.replayCache;
  // States are keyed by everything that determines them, so an unchanged prefix of an
  // edited history (or of a parameter change) is served from the cache instead of re-run.
  let stateKey = cache ? hashText(JSON.stringify({ ...doc, featureHistory: [] })) : '';

  for (const step of history) {
    if (step.suppressed) continue;
    const cmd = getCommandFn(step.name);
    if (!cmd) continue; // Unknown command — skip gracefully.
    const remapped = resolveStepForReplay(step, doc, idMap, resolveWarnings, 'step');
    const before = doc;
    let key = cache ? nextStateKey(stateKey, step.id, step.name, remapped) : '';
    const hit = cache?.get(key);
    if (hit !== undefined) {
      doc = { ...hit.doc, featureHistory: history };
      idMap = new Map(hit.idMap);
    } else {
      const uidBefore = doc.building?.uid;
      const result = runReplayStep(cmd, step, doc, remapped, idMap, context, true);
      // Accept the new geometry but keep OUR featureHistory intact.
      if (result) doc = { ...result.document, featureHistory: history };
      const mintedUid = uidBefore === undefined ? doc.building?.uid : undefined;
      if (mintedUid === undefined) {
        cache?.set(key, { doc, idMap: new Map(idMap) });
      } else if (cache) {
        // The step minted a globally unique id (uniqueId): never memoize it, and key every later
        // state by that id so no other document is served this document's identity.
        key = nextStateKey(key, 'minted-uid', mintedUid, null);
      }
    }
    stateKey = key;
    onStep?.({
      step,
      rawParams: remapIds(step.params, idMap),
      params: remapped,
      before,
      after: doc,
    });
  }

  return doc;
}

// ---------------------------------------------------------------------------
// replay_history
// ---------------------------------------------------------------------------

/**
 * @command replay_history
 * @pure
 * @layer core/commands
 * @affects regenerates all entities from the featureHistory list
 * @invariant featureHistory is preserved unchanged; entities are re-evaluated
 * @failure empty history -> returns doc unchanged, affected:[]
 */
const replayHistory_cmd = defineCommand({
  name: 'replay_history',
  description:
    'Recompute the document from scratch by replaying all non-suppressed steps in ' +
    'featureHistory in order. Use after manually editing the history list or to ' +
    'verify the document is consistent with its feature recipe.',
  params: z.object({}),
  annotations: { metaHistory: true, idempotent: true },
  run: (doc, _params): CommandResult => {
    if (doc.featureHistory.length === 0) {
      return {
        document: doc,
        summary: 'replay_history: featureHistory is empty — nothing to replay.',
        affected: [],
      };
    }
    const warnings: string[] = [];
    const refused = kernelRefusal(doc, doc.featureHistory);
    if (refused !== null) {
      return { document: doc, summary: `replay_history: ${refused}`, affected: [] };
    }
    const regenerated = replayHistory(doc, doc.featureHistory, currentContext().registry, warnings);
    const count = Object.keys(regenerated.entities).length;
    const warnSuffix =
      warnings.length > 0
        ? ` Unresolved expressions (${warnings.length}): ${warnings.join('; ')}.`
        : '';
    return {
      document: regenerated,
      summary: `replay_history: replayed ${doc.featureHistory.length} step(s); ${count} ${count === 1 ? 'entity' : 'entities'} in document.${warnSuffix}`,
      affected: regenerated.order,
    };
  },
});

// ---------------------------------------------------------------------------
// set_step_suppressed
// ---------------------------------------------------------------------------

/**
 * @command set_step_suppressed
 * @pure
 * @layer core/commands
 * @affects toggles suppressed flag on a FeatureStep then regenerates the document
 * @invariant featureHistory length is unchanged
 * @failure unknown stepId -> no-op, affected:[]
 */
const setStepSuppressed = defineCommand({
  name: 'set_step_suppressed',
  description:
    'Toggle the suppressed flag of a feature history step by its stepId. ' +
    'A suppressed step is skipped during replay, effectively hiding its contribution ' +
    'without deleting it. The document is regenerated after the flag is changed.',
  params: z.object({
    stepId: z
      .string()
      .describe(
        'Id of the FeatureStep to suppress or un-suppress (from doc.featureHistory[*].id).',
      ),
    suppressed: z.boolean().describe('true to suppress (skip during replay), false to restore.'),
  }),
  annotations: { metaHistory: true, idempotent: true },
  run: (doc, { stepId, suppressed }): CommandResult => {
    const idx = doc.featureHistory.findIndex((s) => s.id === stepId);
    if (idx === -1) {
      return {
        document: doc,
        summary: `set_step_suppressed: step '${stepId}' not found in featureHistory.`,
        affected: [],
      };
    }
    const updatedStep: FeatureStep = { ...doc.featureHistory[idx]!, suppressed };
    const newHistory = [
      ...doc.featureHistory.slice(0, idx),
      updatedStep,
      ...doc.featureHistory.slice(idx + 1),
    ];
    const refused = kernelRefusal(doc, newHistory);
    if (refused !== null) {
      return { document: doc, summary: `set_step_suppressed: ${refused}`, affected: [] };
    }
    const regenerated = replayHistory(doc, newHistory, currentContext().registry);
    const count = Object.keys(regenerated.entities).length;
    return {
      document: regenerated,
      summary: `set_step_suppressed: step '${stepId}' suppressed=${String(suppressed)}; regenerated ${count} ${count === 1 ? 'entity' : 'entities'}.`,
      affected: regenerated.order,
    };
  },
});

// ---------------------------------------------------------------------------
// edit_step_params
// ---------------------------------------------------------------------------

/**
 * @command edit_step_params
 * @pure
 * @layer core/commands
 * @affects replaces params of a FeatureStep then regenerates the document
 * @invariant featureHistory length is unchanged; step name is unchanged
 * @failure unknown stepId -> no-op, affected:[]
 */
const editStepParams = defineCommand({
  name: 'edit_step_params',
  description:
    'Replace the params of a feature history step by its stepId, then regenerate ' +
    'the document by replaying featureHistory. Use to parametrically edit a past ' +
    'operation (e.g. change the size of a box created earlier).',
  params: z.object({
    stepId: z
      .string()
      .describe(
        'Id of the FeatureStep whose params are to be replaced (from doc.featureHistory[*].id).',
      ),
    params: z
      .object({})
      .describe(
        'New params object for the step. Must be compatible with the command named in the step ' +
          '(i.e. a valid params object for step.name). The document is regenerated after replacement.',
      ),
  }),
  annotations: { metaHistory: true, idempotent: true },
  run: (doc, { stepId, params: newParams }): CommandResult => {
    const idx = doc.featureHistory.findIndex((s) => s.id === stepId);
    if (idx === -1) {
      return {
        document: doc,
        summary: `edit_step_params: step '${stepId}' not found in featureHistory.`,
        affected: [],
      };
    }
    const updatedStep: FeatureStep = { ...doc.featureHistory[idx]!, params: newParams };
    const newHistory = [
      ...doc.featureHistory.slice(0, idx),
      updatedStep,
      ...doc.featureHistory.slice(idx + 1),
    ];
    const refused = kernelRefusal(doc, newHistory);
    if (refused !== null) {
      return { document: doc, summary: `edit_step_params: ${refused}`, affected: [] };
    }
    const regenerated = replayHistory(doc, newHistory, currentContext().registry);
    const count = Object.keys(regenerated.entities).length;
    return {
      document: regenerated,
      summary: `edit_step_params: step '${stepId}' params updated; regenerated ${count} ${count === 1 ? 'entity' : 'entities'}.`,
      affected: regenerated.order,
    };
  },
});

// ---------------------------------------------------------------------------
// reorder_step
// ---------------------------------------------------------------------------

/**
 * @command reorder_step
 * @pure
 * @layer core/commands
 * @affects moves a FeatureStep to a new index then regenerates the document
 * @invariant featureHistory length is unchanged
 * @failure unknown stepId -> no-op, affected:[]
 */
const reorderStep = defineCommand({
  name: 'reorder_step',
  description:
    'Move a feature history step to a new position (0-based index) in the featureHistory ' +
    'list, then regenerate the document. Use to change the order in which operations are applied.',
  params: z.object({
    stepId: z.string().describe('Id of the FeatureStep to move (from doc.featureHistory[*].id).'),
    newIndex: z
      .number()
      .describe(
        'Zero-based target index in featureHistory. Clamped to [0, history.length-1]. ' +
          'Moving to the same index is a no-op.',
      ),
  }),
  annotations: { metaHistory: true, idempotent: true },
  run: (doc, { stepId, newIndex }): CommandResult => {
    const idx = doc.featureHistory.findIndex((s) => s.id === stepId);
    if (idx === -1) {
      return {
        document: doc,
        summary: `reorder_step: step '${stepId}' not found in featureHistory.`,
        affected: [],
      };
    }
    const clamped = Math.max(0, Math.min(newIndex, doc.featureHistory.length - 1));
    if (clamped === idx) {
      return {
        document: doc,
        summary: `reorder_step: step '${stepId}' is already at index ${idx}.`,
        affected: [],
      };
    }
    const step = doc.featureHistory[idx]!;
    const without = [...doc.featureHistory.slice(0, idx), ...doc.featureHistory.slice(idx + 1)];
    const newHistory = [...without.slice(0, clamped), step, ...without.slice(clamped)];
    const refused = kernelRefusal(doc, newHistory);
    if (refused !== null) {
      return { document: doc, summary: `reorder_step: ${refused}`, affected: [] };
    }
    const regenerated = replayHistory(doc, newHistory, currentContext().registry);
    const count = Object.keys(regenerated.entities).length;
    return {
      document: regenerated,
      summary: `reorder_step: step '${stepId}' moved from index ${idx} to ${clamped}; regenerated ${count} ${count === 1 ? 'entity' : 'entities'}.`,
      affected: regenerated.order,
    };
  },
});

// ---------------------------------------------------------------------------
// delete_step
// ---------------------------------------------------------------------------

/**
 * @command delete_step
 * @pure
 * @layer core/commands
 * @affects removes a FeatureStep from featureHistory then regenerates the document
 * @invariant featureHistory length decreases by 1
 * @failure unknown stepId -> no-op, affected:[]
 */
const deleteStep = defineCommand({
  name: 'delete_step',
  description:
    'Permanently remove a feature history step by its stepId from featureHistory, ' +
    'then regenerate the document. Unlike set_step_suppressed, this cannot be undone ' +
    'through the history API (use undo/redo stack instead).',
  params: z.object({
    stepId: z.string().describe('Id of the FeatureStep to delete (from doc.featureHistory[*].id).'),
  }),
  annotations: { metaHistory: true, destructive: true },
  run: (doc, { stepId }): CommandResult => {
    const idx = doc.featureHistory.findIndex((s) => s.id === stepId);
    if (idx === -1) {
      return {
        document: doc,
        summary: `delete_step: step '${stepId}' not found in featureHistory.`,
        affected: [],
      };
    }
    const newHistory = doc.featureHistory.filter((s) => s.id !== stepId);
    const refused = kernelRefusal(doc, newHistory);
    if (refused !== null) {
      return { document: doc, summary: `delete_step: ${refused}`, affected: [] };
    }
    const regenerated = replayHistory(doc, newHistory, currentContext().registry);
    const count = Object.keys(regenerated.entities).length;
    return {
      document: regenerated,
      summary: `delete_step: step '${stepId}' deleted; regenerated ${count} ${count === 1 ? 'entity' : 'entities'}.`,
      affected: regenerated.order,
    };
  },
});

// ---------------------------------------------------------------------------
// insert_step
// ---------------------------------------------------------------------------

/**
 * @command insert_step
 * @pure
 * @layer core/commands
 * @affects splices a new FeatureStep into featureHistory then regenerates the document
 * @invariant featureHistory length increases by 1
 * @failure afterStepId provided but not found -> no-op, affected:[]
 */
const insertStep = defineCommand({
  name: 'insert_step',
  description:
    'Splice a new feature history step into featureHistory immediately after the step ' +
    'with id afterStepId, then regenerate the document. If afterStepId is omitted the ' +
    'step is appended at the end. The new step is always active (suppressed=false).',
  params: z.object({
    afterStepId: z
      .string()
      .optional()
      .describe(
        'Id of the existing FeatureStep after which to insert the new step. ' +
          'If omitted, the new step is appended at the end of featureHistory.',
      ),
    name: z
      .string()
      .describe(
        'Registry command name (snake_case) for the new step, e.g. "add_box". ' +
          'Must be a known command name; unknown names are stored but skipped during replay.',
      ),
    params: z
      .object({})
      .describe(
        'Params object for the command named in `name`. Must be compatible with that command.',
      ),
    label: z
      .string()
      .optional()
      .describe('Optional human/AI-readable label for this step, e.g. "Base plate".'),
  }),
  annotations: { metaHistory: true, idempotent: true },
  run: (doc, { afterStepId, name: cmdName, params: stepParams, label }): CommandResult => {
    if (afterStepId !== undefined) {
      const exists = doc.featureHistory.some((s) => s.id === afterStepId);
      if (!exists) {
        return {
          document: doc,
          summary: `insert_step: afterStepId '${afterStepId}' not found in featureHistory.`,
          affected: [],
        };
      }
    }

    const stepNumber = doc.nextStepNumber ?? 1;
    const newStep: FeatureStep = {
      id: `step-${stepNumber}`,
      name: cmdName,
      params: stepParams,
      suppressed: false,
      ...(label !== undefined ? { label } : {}),
    };

    let newHistory: FeatureStep[];
    if (afterStepId === undefined) {
      newHistory = [...doc.featureHistory, newStep];
    } else {
      const insertIdx = doc.featureHistory.findIndex((s) => s.id === afterStepId);
      newHistory = [
        ...doc.featureHistory.slice(0, insertIdx + 1),
        newStep,
        ...doc.featureHistory.slice(insertIdx + 1),
      ];
    }

    const refused = kernelRefusal(doc, newHistory);

    if (refused !== null) {
      return { document: doc, summary: `insert_step: ${refused}`, affected: [] };
    }

    const regenerated = {
      ...replayHistory(doc, newHistory, currentContext().registry),
      nextStepNumber: stepNumber + 1,
    };
    const count = Object.keys(regenerated.entities).length;
    return {
      document: regenerated,
      summary: `insert_step: step '${newStep.id}' (${cmdName}) inserted; regenerated ${count} ${count === 1 ? 'entity' : 'entities'}.`,
      affected: regenerated.order,
    };
  },
});

// ---------------------------------------------------------------------------
// Convenience re-export — typed as CommandDefinition<unknown> for registry.ts
// ---------------------------------------------------------------------------

export const historyCommands: ReadonlyArray<CommandDefinition<unknown>> = [
  replayHistory_cmd,
  setStepSuppressed,
  editStepParams,
  reorderStep,
  deleteStep,
  insertStep,
] as ReadonlyArray<CommandDefinition<unknown>>;
