/**
 * Replay state classification (architecture L8).
 *
 * REGENERATED by replay (constructive, produced by recorded steps): entities, order,
 * selection, materials, components, constraints(+Order), joints(+Order),
 * driveRelations(+Order), featureHistory.
 * CARRIED from base (document-level inputs written by metaHistory commands): camera, units,
 * displayPrecision, parameters, animations, groups, layers, layerOrder, configurations, recipes.
 * ORPHANS: entries in a regenerated table that no base history step produced (e.g. loaded
 * or seeded outside history). They would be lost by replay, so they are seeded into the
 * fresh document.
 *
 * @layer core/commands
 */

import type { CadDocument, FeatureStep } from '../model/types';

function affectedIds(history: FeatureStep[]): Set<string> {
  const ids = new Set<string>();
  for (const step of history) for (const id of step.affected ?? []) ids.add(id);
  return ids;
}

function paramString(step: FeatureStep, key: string): string | undefined {
  const params: unknown = step.params;
  if (typeof params !== 'object' || params === null) return undefined;
  const value = (params as Record<string, unknown>)[key];
  return typeof value === 'string' ? value : undefined;
}

type OrderedTable = 'constraints' | 'joints' | 'driveRelations';
const ORDER_KEY = {
  constraints: 'constraintOrder',
  joints: 'jointOrder',
  driveRelations: 'driveRelationOrder',
} as const;

/** @pure returns the regenerated-table seed (orphans only) to merge into a fresh document. */
export function orphanState(
  base: CadDocument,
): Pick<
  CadDocument,
  | 'materials'
  | 'components'
  | 'constraints'
  | 'constraintOrder'
  | 'joints'
  | 'jointOrder'
  | 'driveRelations'
  | 'driveRelationOrder'
> {
  const history = base.featureHistory;
  const affected = affectedIds(history);

  const materialClaims = new Set(
    history.filter((s) => s.name === 'create_material').map((s) => paramString(s, 'name')),
  );
  const materials = Object.fromEntries(
    Object.entries(base.materials).filter(([key]) => !materialClaims.has(key)),
  );

  const componentSteps = history.filter((s) => s.name === 'create_component');
  const componentClaims = new Set<string | undefined>();
  let unattributable = 0;
  for (const step of componentSteps) {
    const explicit = paramString(step, 'componentId');
    if (explicit !== undefined) {
      componentClaims.add(explicit);
      continue;
    }
    const instance = step.affected?.[0] !== undefined ? base.entities[step.affected[0]] : undefined;
    if (instance?.kind === 'instance') componentClaims.add(instance.componentId);
    else unattributable++;
  }
  const components =
    unattributable > 0
      ? {}
      : Object.fromEntries(
          Object.entries(base.components).filter(([key]) => !componentClaims.has(key)),
        );

  const seed = {
    constraints: {} as CadDocument['constraints'],
    constraintOrder: [] as string[],
    joints: {} as CadDocument['joints'],
    jointOrder: [] as string[],
    driveRelations: {} as CadDocument['driveRelations'],
    driveRelationOrder: [] as string[],
  };
  for (const table of ['constraints', 'joints', 'driveRelations'] as OrderedTable[]) {
    const orderKey = ORDER_KEY[table];
    const orphanIds = base[orderKey].filter((id) => !affected.has(id) && id in base[table]);
    (seed[table] as Record<string, unknown>) = Object.fromEntries(
      orphanIds.map((id) => [id, base[table][id]]),
    );
    seed[orderKey] = orphanIds;
  }

  return { materials, components, ...seed };
}
