/**
 * OpenSCAD emitter: FeatureProgram → a .scad file. Parameters become top-level variables
 * (Customizer-friendly); every feature version becomes a module so booleans and edits keep order.
 *
 * @layer core/codegen
 * @pure
 */

import type { Feature, FeatureProgram, ShapeSpec, Term, Term2, Term3 } from './program';
import {
  commentText,
  featureLinesWithHeadings,
  formatDegrees,
  formatNumber,
  formatTerm,
  isZero,
  numberRows,
  provenance,
  quote,
  parameterLines,
} from './format';

function vector(terms: readonly Term[]): string {
  return `[${terms.map(formatTerm).join(', ')}]`;
}

function polygon(profile: readonly Term2[]): string {
  return `polygon([${profile.map(vector).join(', ')}])`;
}

function half(term: Term): string {
  return term.expression !== undefined ? `(${term.expression}) / 2` : formatNumber(term.value / 2);
}

function negHalf(term: Term): string {
  return term.expression !== undefined
    ? `-(${term.expression}) / 2`
    : formatNumber(-term.value / 2);
}

function meshPolyhedron(positions: readonly number[]): string {
  const vertexCount = positions.length / 3;
  const faces: string[] = [];
  // OpenSCAD wants clockwise faces seen from outside; llull triangles are counter-clockwise.
  for (let i = 0; i + 2 < vertexCount; i += 3) faces.push(`[${i}, ${i + 2}, ${i + 1}]`);
  const points = numberRows(positions, 3).map((row) => `[${row}]`);
  return `polyhedron(points = [\n    ${points.join(',\n    ')}\n  ], faces = [${faces.join(', ')}])`;
}

function shapeSource(shape: ShapeSpec): string {
  switch (shape.kind) {
    case 'box':
      return `cube(${vector(shape.size)}, center = true)`;
    case 'cylinder':
      return `cylinder(h = ${formatTerm(shape.height)}, r = ${formatTerm(shape.radius)}, center = true)`;
    case 'sphere':
      return `sphere(r = ${formatTerm(shape.radius)})`;
    case 'cone':
      return `cylinder(h = ${formatTerm(shape.height)}, r1 = ${formatTerm(shape.radius)}, r2 = 0)`;
    case 'torus':
      return `rotate_extrude() translate([${formatTerm(shape.ringRadius)}, 0]) circle(r = ${formatTerm(shape.tubeRadius)})`;
    case 'wedge': {
      const [w, h, d] = shape.size.map(formatTerm) as [string, string, string];
      return `rotate([90, 0, 90]) linear_extrude(height = ${w}) polygon([[0, 0], [${h}, 0], [0, ${d}]])`;
    }
    case 'pyramid': {
      const [x0, x1] = [negHalf(shape.baseWidth), half(shape.baseWidth)];
      const [y0, y1] = [negHalf(shape.baseDepth), half(shape.baseDepth)];
      const h = formatTerm(shape.height);
      return (
        `polyhedron(points = [[${x0}, ${y0}, 0], [${x1}, ${y0}, 0], [${x1}, ${y1}, 0], [${x0}, ${y1}, 0], [0, 0, ${h}]], ` +
        `faces = [[0, 1, 2, 3], [0, 4, 1], [1, 4, 2], [2, 4, 3], [3, 4, 0]])`
      );
    }
    case 'extrusion':
      return `linear_extrude(height = ${formatTerm(shape.depth)}) ${polygon(shape.profile)}`;
    case 'revolution': {
      const angle = formatDegrees(shape.angle, 'PI');
      const body = (sweep: string): string =>
        `rotate_extrude(angle = ${sweep}) ${polygon(shape.profile)}`;
      if (shape.axis === 'x') return `rotate([90, 0, 90]) ${body(angle)}`;
      if (shape.axis === 'y') return `rotate([-90, 0, 0]) ${body(`-(${angle})`)}`;
      return body(angle);
    }
    case 'mesh':
      return meshPolyhedron(shape.positions);
  }
}

function placed(source: string, position: Term3, rotation: Term3): string {
  let text = source;
  const [rx, ry, rz] = rotation.map((r) => formatDegrees(r, 'PI')) as [string, string, string];
  // llull applies Rz, then Ry, then Rx: nest so the innermost rotation runs first.
  if (!isZero([rotation[2]])) text = `rotate([0, 0, ${rz}]) ${text}`;
  if (!isZero([rotation[1]])) text = `rotate([0, ${ry}, 0]) ${text}`;
  if (!isZero([rotation[0]])) text = `rotate([${rx}, 0, 0]) ${text}`;
  if (!isZero(position)) text = `translate(${vector(position)}) ${text}`;
  return text;
}

const OPERATIONS: Readonly<Record<'union' | 'cut' | 'intersect', string>> = {
  union: 'union',
  cut: 'difference',
  intersect: 'intersection',
};

/** Emit an OpenSCAD program; returns the source text. */
export function emitOpenScad(program: FeatureProgram): string {
  const lines: string[] = [
    '// llull model — generated by llull export_code (OpenSCAD).',
    ...provenance(program).map((line) => `// ${line}`),
    '// Rotations are in degrees. Each feature version is a module; the final solids are',
    '// instantiated at the end. Edit the parameters below (OpenSCAD Customizer-ready).',
    '',
    '$fn = 96;',
    '',
    '/* [Parameters] */',
  ];
  lines.push(
    ...parameterLines(
      program,
      '//',
      (p) =>
        `${p.identifier} = ${p.expression ?? formatNumber(p.value)}; // ${commentText(p.name)}`,
    ),
  );
  lines.push('', '/* [Hidden] */', '');

  const version = new Map<string, number>();
  const current = (variable: string): string => `${variable}_v${version.get(variable) ?? 0}`;
  const next = (variable: string): string => {
    version.set(variable, (version.get(variable) ?? 0) + 1);
    return current(variable);
  };

  const featureLine = (feature: Feature): string => {
    const v = feature.variable;
    switch (feature.op) {
      case 'solid': {
        const body = placed(shapeSource(feature.shape), feature.position, feature.rotation);
        return `module ${next(v)}() ${body};`;
      }
      case 'boolean': {
        const left = current(feature.left);
        const right = current(feature.right);
        return `module ${next(v)}() ${OPERATIONS[feature.kind]}() { ${left}(); ${right}(); }`;
      }
      case 'fillet':
      case 'chamfer':
      case 'shell': {
        // OpenSCAD has no fillets: the exact result's triangles stand in.
        if (feature.mesh === undefined) return `// ${v}: ${feature.op} not expressible in OpenSCAD`;
        return `module ${next(v)}() ${shapeSource({ kind: 'mesh', positions: feature.mesh })};`;
      }
      case 'translate': {
        const previous = current(v);
        return `module ${next(v)}() translate(${vector(feature.delta)}) ${previous}();`;
      }
      case 'remove':
        return `// ${v} removed`;
      case 'label':
        return `// ${v} labelled ${quote(feature.name)}`;
    }
  };
  lines.push(...featureLinesWithHeadings(program, '//', featureLine));

  lines.push('', '// ── result ──');
  for (const output of program.outputs) {
    const label = output.name !== undefined ? ` // ${commentText(output.name)}` : '';
    lines.push(`color(${quote(output.color)}) ${current(output.variable)}();${label}`);
  }
  lines.push('');
  return lines.join('\n');
}
