/**
 * CadQuery / build123d emitter: FeatureProgram → a standalone, traced Python script.
 *
 * @layer core/codegen
 * @pure
 * @invariant running the script records LLULL_TRACE, which apply_code_trace turns back into the same
 *   llull feature history (parameters + expressions + order) — the code is a round-trippable recipe.
 */

import type { Feature, FeatureProgram } from './program';
import {
  featureLinesWithHeadings,
  formatNumber,
  parameterLines,
  provenance,
  quote,
  sectionBanner,
} from './format';
import { placementKwargs, pythonTuple, shapeCallOpen } from './pythonCalls';
import { pythonRuntime, type PythonBackend } from './pythonRuntime';

const LIBRARY: Readonly<Record<PythonBackend, string>> = {
  cadquery: 'CadQuery',
  build123d: 'build123d',
};

function featureLine(feature: Feature): string {
  const v = feature.variable;
  switch (feature.op) {
    case 'solid': {
      const name = feature.name !== undefined ? `, name=${quote(feature.name)}` : '';
      const place = placementKwargs(feature.shape, feature.position, feature.rotation);
      return `${v} = ${shapeCallOpen(feature.shape)}${place}, color=${quote(feature.color)}${name})`;
    }
    case 'boolean':
      return `${v} = ${feature.kind}(${feature.left}, ${feature.right})`;
    case 'translate':
      return `${v} = translate(${v}, ${pythonTuple(feature.delta)})`;
    case 'remove':
      return `remove(${v})`;
    case 'label':
      return `label(${v}, ${quote(feature.name)})`;
  }
}

function header(program: FeatureProgram, backend: PythonBackend): string {
  return [
    '"""',
    `llull model — generated by llull export_code (${LIBRARY[backend]}).`,
    '',
    ...provenance(program),
    'Positions are in document units; rotations are XYZ Euler angles in DEGREES',
    '(applied about Z, then Y, then X, around the solid origin).',
    '',
    'Edit PARAMETERS and MODEL, then either:',
    '  * run `python <this file>` to write model.step, or',
    "  * send it back with llull's import_code tool: parameters, expressions and",
    '    feature order are rebuilt as an editable llull feature history.',
    'Raw library code is welcome too: wrap a shape with custom(shape) to include it.',
    '"""',
  ].join('\n');
}

/** Emit a runnable CadQuery or build123d script for the program. */
export function emitPython(program: FeatureProgram, backend: PythonBackend): string {
  const lines: string[] = [header(program, backend), ''];
  lines.push(`LLULL_UNITS = ${quote(program.units)}`, '');
  lines.push(`# ── llull runtime (${LIBRARY[backend]}) · keep unchanged ${'─'.repeat(30)}`);
  lines.push(pythonRuntime(backend));
  lines.push(sectionBanner('PARAMETERS'));
  lines.push(
    ...parameterLines(
      program,
      '#',
      (p) => `${p.identifier} = param(${quote(p.name)}, ${p.expression ?? formatNumber(p.value)})`,
    ),
  );
  lines.push('', sectionBanner('MODEL'));
  lines.push(...featureLinesWithHeadings(program, '#', featureLine));
  lines.push(
    '',
    'result = finish()',
    '',
    'if __name__ == "__main__":',
    '    export_step(result, "model.step")',
    'elif "show_object" in globals():',
    '    show_object(result)  # noqa: F821 (CQ-editor)',
    '',
  );
  return lines.join('\n');
}
