/**
 * Keeps evaluated civil geometry consistent with the civil model (architecture L4/L8), and lists
 * the references between civil objects.
 * @layer domain-aec/civil
 */

import type { DerivationGuard } from '@core/commands/derivation';
import type { CadDocument, Entity } from '@core/model/types';
import type { CivilModel, CivilObject } from '@core/model/civil';

function civilTag(entity: Entity | undefined): string | null {
  const tag = entity?.tags?.find((candidate) => candidate.startsWith('civil:'));
  return tag ? tag.slice('civil:'.length) : null;
}

function sameEntity(a: Entity | undefined, b: Entity | undefined): boolean {
  return a === b || (a !== undefined && b !== undefined && JSON.stringify(a) === JSON.stringify(b));
}

/** Ids of civil objects whose generated entities `next` changed, removed or copied directly. */
function editedCivilObjects(previous: CadDocument, next: CadDocument): string[] {
  if (next.civil !== previous.civil || previous.civil === undefined) return [];
  if (next.entities === previous.entities) return [];
  const edited = new Set<string>();
  const owned = new Set<string>();
  for (const object of Object.values(previous.civil.objects)) {
    for (const id of object.entityIds) {
      owned.add(id);
      if (!sameEntity(next.entities[id], previous.entities[id])) edited.add(object.id);
    }
  }
  for (const [id, entity] of Object.entries(next.entities)) {
    if (owned.has(id) || previous.entities[id] !== undefined) continue;
    const object = civilTag(entity);
    if (entity.tags?.includes('civil') === true && object !== null) edited.add(object);
  }
  return [...edited];
}

/** Entities generated by civil objects change only through civil commands. */
export const civilDerivationGuard: DerivationGuard = {
  domain: 'civil',
  check(previous, next) {
    const edited = editedCivilObjects(previous, next);
    if (edited.length === 0) return null;
    return (
      `it would edit geometry generated by civil object(s) ${edited.join(', ')}. ` +
      'Edit the object with a civil command instead (update_surface, update_platform, update_alignment, delete_civil_object, …).'
    );
  },
};

/** Ids of the civil objects `object` depends on. */
export function referencesOf(object: CivilObject): string[] {
  switch (object.category) {
    case 'surface':
      return [...object.pointGroupIds];
    case 'platform':
      return [object.surfaceId];
    case 'alignment':
      return object.surfaceId !== undefined ? [object.surfaceId] : [];
    case 'pipe':
      return [object.fromId, object.toId];
    case 'pointGroup':
    case 'manhole':
      return [];
  }
}

/** Ids of the objects that reference `id`, in model order. */
export function dependentsOf(civil: CivilModel, id: string): string[] {
  return civil.order.filter((candidate) => {
    const object = civil.objects[candidate];
    return object !== undefined && referencesOf(object).includes(id);
  });
}

/** Civil object that generated `entityId` (verified against the object's entity list). */
export function civilObjectOf(
  document: Pick<CadDocument, 'entities' | 'civil'>,
  entityId: string,
): string | null {
  const id = civilTag(document.entities[entityId]);
  if (id === null) return null;
  return document.civil?.objects[id]?.entityIds.includes(entityId) === true ? id : null;
}
