/**
 * Shared plumbing for plugins that derive layers and geometry from a model: layer sync, load-time
 * restore merge, and detection of direct edits to derived entities.
 * @layer domain-aec
 * @pure
 */

import type { CadDocument, Entity, Layer } from '@core/model/types';

/** Adds layers referenced by `layerIds` that the document lacks (name from id, colour by id). */
export function ensureLayerIds(
  layers: Record<string, Layer>,
  layerOrder: string[],
  layerIds: Iterable<string>,
  colors: ReadonlyMap<string, string>,
): { layers: Record<string, Layer>; layerOrder: string[] } {
  let nextLayers = layers;
  let nextOrder = layerOrder;
  for (const id of layerIds) {
    if (nextLayers[id]) continue;
    const name = id.replace(/^layer-/, '');
    const color = colors.get(id) ?? '#8a8a8a';
    nextLayers = { ...nextLayers, [id]: { id, name, visible: true, locked: false, color } };
    nextOrder = [...nextOrder, id];
  }
  return { layers: nextLayers, layerOrder: nextOrder };
}

/**
 * Replaces the entities generated by `previous` owners with a fresh `evaluate` of each `current`
 * owner (in order), syncing layers and selection.
 * @returns the document parts to spread plus the owners re-keyed with their new `entityIds`
 */
export function regenerateOwned<
  T extends { readonly id: string; readonly entityIds: readonly string[] },
>(
  doc: CadDocument,
  previous: Iterable<T>,
  current: Iterable<T>,
  evaluate: (owner: T) => Entity[],
  colors: ReadonlyMap<string, string>,
): {
  parts: Pick<CadDocument, 'entities' | 'order' | 'layers' | 'layerOrder' | 'selection'>;
  owners: Record<string, T>;
} {
  const stale = new Set<string>();
  for (const owner of previous) for (const id of owner.entityIds) stale.add(id);
  const entities: Record<string, Entity> = {};
  for (const [id, entity] of Object.entries(doc.entities)) {
    if (!stale.has(id)) entities[id] = entity;
  }
  const order = doc.order.filter((id) => !stale.has(id));
  const owners: Record<string, T> = {};
  const usedLayers = new Set<string>();
  for (const owner of current) {
    const generated = evaluate(owner);
    for (const entity of generated) {
      entities[entity.id] = entity;
      order.push(entity.id);
      usedLayers.add(entity.layerId);
    }
    owners[owner.id] = { ...owner, entityIds: generated.map((entity) => entity.id) };
  }
  const { layers, layerOrder } = ensureLayerIds(doc.layers, doc.layerOrder, usedLayers, colors);
  const selection = doc.selection.filter((id) => entities[id] !== undefined);
  return { parts: { entities, order, layers, layerOrder, selection }, owners };
}

/** Saved draw order first (ids still present), regenerated ids after; selection filtered likewise. */
export function mergeRestored(
  raw: Record<string, unknown>,
  savedOrder: readonly string[],
  regenerated: CadDocument,
): { entities: CadDocument['entities']; order: string[]; selection: string[] } {
  const present = savedOrder.filter((id) => id in regenerated.entities);
  const placed = new Set(present);
  const order = [...present, ...regenerated.order.filter((id) => !placed.has(id))];
  const selection = Array.isArray(raw['selection'])
    ? (raw['selection'] as string[]).filter((id) => id in regenerated.entities)
    : [];
  return { entities: regenerated.entities, order, selection };
}

export function ownerTag(entity: Entity | undefined, prefix: string): string | null {
  const tag = entity?.tags?.find((candidate) => candidate.startsWith(`${prefix}:`));
  return tag ? tag.slice(prefix.length + 1) : null;
}

function sameEntity(a: Entity | undefined, b: Entity | undefined): boolean {
  return a === b || (a !== undefined && b !== undefined && JSON.stringify(a) === JSON.stringify(b));
}

/**
 * @returns ids of owners whose generated entities `next` changed or removed, or that gained a copy
 *          (a new entity tagged `<prefix>:<owner>` plus `marker`).
 */
export function editedOwners(
  owners: Iterable<{ readonly id: string; readonly entityIds: readonly string[] }>,
  previous: Readonly<Record<string, Entity>>,
  next: Readonly<Record<string, Entity>>,
  prefix: string,
  marker: string,
): string[] {
  const edited = new Set<string>();
  const owned = new Set<string>();
  for (const owner of owners) {
    for (const id of owner.entityIds) {
      owned.add(id);
      if (!sameEntity(next[id], previous[id])) edited.add(owner.id);
    }
  }
  for (const [id, entity] of Object.entries(next)) {
    if (owned.has(id) || previous[id] !== undefined) continue;
    const owner = ownerTag(entity, prefix);
    if (entity.tags?.includes(marker) === true && owner !== null) edited.add(owner);
  }
  return [...edited];
}
