/**
 * Keeps evaluated building geometry consistent with the building model (architecture L4/L8).
 * @layer domain-aec
 */

import type { DerivationGuard } from '@core/commands/derivation';
import { editedOwners, ownerTag } from './derived';
import type { CadDocument } from '@core/model/types';

/**
 * @pure
 * @returns ids of building elements whose generated entities `next` changed, removed or copied
 *          without going through a building command (empty when the edit is legal). Commands that
 *          rebuild entity objects without changing them (e.g. solve_constraints) are not flagged.
 */
function editedBuildingElements(previous: CadDocument, next: CadDocument): string[] {
  if (next.building !== previous.building || previous.building === undefined) return [];
  if (next.entities === previous.entities) return [];
  return editedOwners(
    Object.values(previous.building.elements),
    previous.entities,
    next.entities,
    'element',
    'bim',
  );
}

/** Entities generated by building elements change only through building commands. */
export const buildingDerivationGuard: DerivationGuard = {
  domain: 'building',
  check(previous, next) {
    const edited = editedBuildingElements(previous, next);
    if (edited.length === 0) return null;
    return (
      `it would edit geometry generated by building element(s) ${edited.join(', ')}. ` +
      'Edit the element instead (update_wall, update_opening, update_level, move_building_element, delete_building_element, …).'
    );
  },
};

/** Building element that generated `entityId` (verified against the element's entity list). */
export function buildingElementOf(
  document: Pick<CadDocument, 'entities' | 'building'>,
  entityId: string,
): string | null {
  const element = ownerTag(document.entities[entityId], 'element');
  if (element === null) return null;
  return document.building?.elements[element]?.entityIds.includes(entityId) === true
    ? element
    : null;
}
